services:

  controller:
    build: ./controller
    container_name: controller
    hostname: controller
    tty: true
    stdin_open: true

    ports:
      - "3220:22"

    volumes:
      - ./controller:/ansible

    networks:
      - ansible-net

  web1:
    build: ./node
    container_name: web1
    hostname: web1

    ports:
      - "3221:22"
      - "8083:80"

    networks:
      - ansible-net

  web2:
    build: ./node
    container_name: web2
    hostname: web2

    ports:
      - "3222:22"
      - "8084:80"

    networks:
      - ansible-net

  web3:
    build: ./node
    container_name: web3
    hostname: web3

    ports:
      - "3223:22"
      - "8086:80"

    networks:
      - ansible-net

  db1:
    build: ./db
    container_name: db1
    hostname: db1

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankingdb

    ports:
      - "5432:5432"
      - "3224:22"

    volumes:
      - ../Banking-App/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    networks:
      - ansible-net

  mon1:
    build: ./node
    container_name: mon1
    hostname: mon1

    ports:
      - "3225:22"
      - "6565:6565"

    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge

    ipam:
      config:
        - subnet: 10.77.77.0/24
