---
- name: Handler demo
  hosts: web
  become: yes

  vars_files:
    - ../vars/vars.yml

  tasks:

    - name: Deploy nginx config
      template:
        src: ../templates/nginx-site.conf.j2
        dest: /etc/nginx/sites-enabled/default
      notify:
        - Restart nginx

  handlers:

    - name: Restart nginx
      shell: service nginx restart
