[all]
controller ansible_host=controller ansible_connection=local
web1 ansible_host=web1
web2 ansible_host=web2
web3 ansible_host=web3
db1 ansible_host=db1
mon1 ansible_host=mon1

[blue]
web1

[green]
web2

[lb]
web3

[databases]
db1

[monitoring]
mon1

[all:vars]
ansible_user=devops
ansible_password=devops123
ansible_connection=ssh
ansible_become_password=devops123
ansible_ssh_common_args=""
#ansible_ssh_common_args="-o StrictHostKeyChecking=no"
